---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install ansible
  yum:
    name: ansible
    state: latest

- name: libselinux-python
  yum:
    name: libselinux-python
    state: latest  

- name: check if key file exists
  stat:
    path: ~/.ssh/id_rsa
  register: _key_exists

- debug: var=_key_exists.stat.exists

- name: generate ssh key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
  when: _key_exists.stat.exists == false
